[build]
  base = "frontend"
  command = "yarn install --frozen-lockfile || yarn install && yarn build"
  publish = "frontend/build"

[[redirects]]
  from = "/api/*"
  to = "https://agenda-boa-production.up.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
