[build]
base = "frontend"
publish = "build"
command = "yarn install --frozen-lockfile || yarn install && yarn build"

[build.environment]
  NODE_VERSION = "20"
  CI = "false"

[[redirects]]
  from = "/api/*"
  to = "https://agenda-boa-production.up.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
