# frontend/netlify.toml
[build]
base = "."
publish = "build"
command = "yarn install --frozen-lockfile || yarn install && yarn build"

# Proxy da API para o Railway
[[redirects]]
  from = "/api/*"
  to = "https://agenda-boa-production.up.railway.app/api/:splat"
  status = 200
  force = true

# SPA fallback (CRA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
