# frontend/netlify.toml
[build]
base = "."
publish = "build"
command = "yarn install --frozen-lockfile || yarn install && yarn build"

[build.environment]
  NODE_VERSION = "20"
  CI = "false"            # evita falha por warnings do CRA na CI

# Proxy das chamadas /api para o Railway
[[redirects]]
  from = "/api/*"
  to = "https://agenda-boa-production.up.railway.app/api/:splat"
  status = 200
  force = true

# SPA fallback (CRA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
