[build]
  base = "frontend"
  publish = "build"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "20"
  REACT_APP_BACKEND_URL = "agenda-boa-production.up.railway.app"

# SPA redirects (se preferir deixar aqui em vez de public/_redirects)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
