[build]
  base = "frontend"
  publish = "build"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "20"

# Proxy sรณ as chamadas de API para o backend do Railway:
[[redirects]]
  from = "/api/*"
  to = "https://agenda-boa-production.up.railway.app/api/:splat"
  status = 200
  force = true

# SPA fallback (CRA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
